# Site settings
name: TWRP Builder
title: TWRP Builder
description: "Jekyll based web site"
baseurl: ""
author: berkantkz
repository: twrpbuilder/twrpbuilder.github.io

# Build settings
markdown: kramdown
permalinks: pretty